class GolemRayURLs:
    CREATE_CLUSTER = '/create_cluster'
    GET_NODES = '/'
    IS_RUNNING = '/is_running'
    IS_TERMINATED = '/is_terminated'
    NODE_TAGS = '/tags'
    INTERNAL_IP = '/internal_ip'
    SET_NODE_TAGS = '/set_tags'
    CREATE_NODES = '/create_nodes'
    TERMINATE_NODES = '/terminate'
