# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/ray/protobuf/runtime_env_common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)src/ray/protobuf/runtime_env_common.proto\x12\x07ray.rpc\"B\n\x0eRuntimeEnvUris\x12\x17\n\x0fworking_dir_uri\x18\x01 \x01(\t\x12\x17\n\x0fpy_modules_uris\x18\x02 \x03(\t\"H\n\x10RuntimeEnvConfig\x12\x1d\n\x15setup_timeout_seconds\x18\x01 \x01(\x05\x12\x15\n\reager_install\x18\x02 \x01(\x08\"\x8e\x01\n\x0eRuntimeEnvInfo\x12\x1e\n\x16serialized_runtime_env\x18\x01 \x01(\t\x12%\n\x04uris\x18\x02 \x01(\x0b\x32\x17.ray.rpc.RuntimeEnvUris\x12\x35\n\x12runtime_env_config\x18\x03 \x01(\x0b\x32\x19.ray.rpc.RuntimeEnvConfig\"\xab\x01\n\x0fRuntimeEnvState\x12\x13\n\x0bruntime_env\x18\x01 \x01(\t\x12\x0f\n\x07ref_cnt\x18\x02 \x01(\x03\x12\x14\n\x07success\x18\x03 \x01(\x08H\x00\x88\x01\x01\x12\x12\n\x05\x65rror\x18\x04 \x01(\tH\x01\x88\x01\x01\x12\x1d\n\x10\x63reation_time_ms\x18\x05 \x01(\x03H\x02\x88\x01\x01\x42\n\n\x08_successB\x08\n\x06_errorB\x13\n\x11_creation_time_msB\x1d\n\x18io.ray.runtime.generated\xf8\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.ray.protobuf.runtime_env_common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030io.ray.runtime.generated\370\001\001'
  _globals['_RUNTIMEENVURIS']._serialized_start=54
  _globals['_RUNTIMEENVURIS']._serialized_end=120
  _globals['_RUNTIMEENVCONFIG']._serialized_start=122
  _globals['_RUNTIMEENVCONFIG']._serialized_end=194
  _globals['_RUNTIMEENVINFO']._serialized_start=197
  _globals['_RUNTIMEENVINFO']._serialized_end=339
  _globals['_RUNTIMEENVSTATE']._serialized_start=342
  _globals['_RUNTIMEENVSTATE']._serialized_end=513
# @@protoc_insertion_point(module_scope)
