name: Code checks and tests

on:
  workflow_call:

jobs:
  build:
    name: Code checks and tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install poetry
        uses: Gr1N/setup-poetry@v9

      - name: Install dependencies
        run: poetry install --no-ansi

      - name: Run checks
        run: poetry run poe checks

      - name: Run tests
        run: poetry run poe tests_unit
