name: Integration tests

on:
  workflow_call:
    inputs:
      BRANCH:
        type: string
        description: Git branch to be used in run
        default: ${{ github.ref }}

jobs:
  examples:
    strategy:
      fail-fast: false
      matrix:
        include:
          - example_name: calculate_pi

          - example_name: hash_cracker_ray_ready
            args: 2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae

          - example_name: mandelbrot_image
            base_yaml_path: examples/mandelbrot.yaml

          - example_name: simple-actor

          - example_name: simple-task

          # Commented out as Goth does not support outbound yet
          # - example_name: dds-with-ray
          #   base_yaml_path: examples/dds-with-ray.yaml
          # - example_name: outbound
          #   base_yaml_path: examples/outbound.yaml
          # - example_name: outbound_tester
          #   base_yaml_path: examples/outbound_tester.yaml

    name: Example ${{ matrix.example_name }} (goth)
    runs-on: goth2
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.BRANCH }}

      - name: Clean up previous runs
        run: |
          pkill -f ray-on-golem || true
          pkill -f goth || true

      - name: Start Goth
        env:
          GOTH_VERSION: 0.16.0
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: ./.github/workflows/start-goth.sh

      - name: Install poetry
        uses: Gr1N/setup-poetry@v9

      - name: Install dependencies
        run: poetry install --no-ansi

      - name: Prepare `golem-cluster.tests.yaml`
        run: |
          poetry run python -m utils.apply_overrides -b ${{ matrix.base_yaml_path || './golem-cluster.yaml' }} golem-cluster.override.2-image.yaml golem-cluster.override.3-disable-stats.yaml golem-cluster.override-goth.yaml -o golem-cluster.tests.yaml
          cat golem-cluster.tests.yaml 

      - name: Call `ray up`
        env:
          PYTHONUNBUFFERED: 1
          RUST_LOG: "INFO,ya_erc20_driver::erc20::wallet=debug"
        run: poetry run ray up golem-cluster.tests.yaml -y --no-config-cache

      - name: Run `examples/${{ matrix.example_name }}.py`
        run: poetry run ray submit golem-cluster.tests.yaml examples/${{ matrix.example_name }}.py -- ${{ matrix.args }}

      - name: Print last cluster logs
        if: always()
        continue-on-error: true
        timeout-minutes: 1
        run: |
          poetry run ray exec golem-cluster.tests.yaml 'ls /tmp/ray/session_latest/logs/'
          poetry run ray exec golem-cluster.tests.yaml 'tail -n 100 /tmp/ray/session_latest/logs/*'

      - name: Call `ray down`
        run: poetry run ray down golem-cluster.tests.yaml -y

      - name: Call `ray-on-golem stop`
        run: poetry run ray-on-golem stop

      - name: Stop Goth
        run: ./.github/workflows/stop-goth.sh

      - name: Prepare artifact name
        run: |
          branch_name = ${{ inputs.BRANCH }}
          branch_name = ${branch_name//\//_}
          echo ARTIFACT_NAME=logs-example-${branch_name}-${{ matrix.example_name }} >> $GITHUB_ENV

      - name: Collects logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: |
            /root/.local/share/ray_on_golem/webserver_debug.log
            /root/.local/share/ray_on_golem/yagna.log
            /tmp/goth-tests
