name: On pull request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  code_tests:
    uses: ./.github/workflows/code_tests.yml
  smoke_tests:
    uses: ./.github/workflows/smoke_tests.yml
