name: On pull request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  code_tests:
    name: Code checks
    uses: ./.github/workflows/code_tests.yml
  integration_tests:
    name: Integration tests
    uses: ./.github/workflows/integration_tests.yml
  smoke_tests:
    name: Smoke tests
    uses: ./.github/workflows/smoke_tests.yml
  ray_deps_test:
    name: Ray deps test
    uses: ./.github/workflows/ray_deps_test.yml
