name: On release

on:
  release:
    types: [prereleased, released]

env:
  PYTHON_VERSION: "3.10"

jobs:
  release_test:
    name: Run checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: Gr1N/setup-poetry@v8

      - run: poetry install

  build:
    needs: [release_test]
    name: Build the release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: Gr1N/setup-poetry@v8

      - name: Get git release tag
        run: echo "::set-output name=git-release-tag::ray-on-golem $(git describe --tags)"
        id: git_describe

      - name: Get package version
        run: echo "::set-output name=poetry-version::$(poetry version)"
        id: poetry_version

      - name: Fail on version mismatch
        run: exit 1
        if:
          ${{ steps.git_describe.outputs.git-release-tag !=
          steps.poetry_version.outputs.poetry-version }}

      - name: Build the release
        run: poetry build

      - name: Store the built package
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  build_test_image:
    name: Build Test VM Image
    needs: [build]
    if: ${{ env.EVENT == 'prereleased' }}
    uses: ./.github/workflows/build_image.yml
    with:
      IS_TEST_BUILD: true
      ENV_PYTHON_VERSION: "3.10"
      IMAGE_PYTHON_VERSION: ${{ vars.PYTHON_VERSION }}
      REGISTRY_REPOSITORY: ${{ vars.REGISTRY_TEST_REPOSITORY }}
    secrets:
      REGISTRY_USER: ${{ secrets.REGISTRY_TEST_USER }}
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TEST_TOKEN }}

  smoke_tests:
    name: Run Smoke Tests
    needs: [build_test_image]
    if: ${{ env.EVENT == 'prereleased' }}
    uses: ./.github/workflows/smoke_tests.yml

  build_image:
    name: Build VM Image
    needs: [build]
    if: ${{ env.EVENT == 'released' }}
    uses: ./.github/workflows/build_image.yml
    with:
      IS_TEST_BUILD: false
      ENV_PYTHON_VERSION: "3.10"
      IMAGE_PYTHON_VERSION: ${{ vars.PYTHON_VERSION }}
      REGISTRY_REPOSITORY: ${{ vars.REGISTRY_REPOSITORY }}
    secrets:
      REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

  test_publish:
    needs: [build_test_image]
    name: Publish the release to test.pypi
    runs-on: ubuntu-latest
    if: ${{ env.EVENT == 'prereleased' }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: Gr1N/setup-poetry@v8

      - name: Retrieve the built package
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Publish to test pypi
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry publish -r testpypi -u __token__ -p ${{ secrets.TESTPYPI_TOKEN }}

  publish:
    needs: [build_image]
    name: Publish the release
    runs-on: ubuntu-latest
    if: ${{ env.EVENT == 'released' }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: Gr1N/setup-poetry@v8

      - name: Retrieve the built package
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Publish to pypi
        run: |
          poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
