name: Nightly

on:
  workflow_call:
  schedule:
    # run this workflow every day at 2:00 AM UTC
    -   cron: '0 2 * * *'

jobs:
  nightly_tests:
    strategy:
      fail-fast: false
      matrix:
        branch: ["main", "develop"]

    steps:
      integration_tests:
        name: Integration tests
        uses: ./.github/workflows/smoke_tests.yml
        with:
          BRANCH: ${{ matrix.branch }}
