name: On schedule

on:
  workflow_dispatch:
  schedule:
    # run this workflow every day at 2:00 AM UTC
    -   cron: '0 2 * * *'

jobs:
  nightly_tests:
    strategy:
      fail-fast: false
      matrix:
        branch: ["main", "develop"]

    steps:
      - name: Integration tests
        uses: ./.github/workflows/smoke_tests.yml
        with:
            BRANCH: ${{ matrix.branch }}
