name: Ray dependencies test

on:
  workflow_call:

jobs:
  build:
    name: Ray dependencies test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install poetry
        uses: Gr1N/setup-poetry@v9

      - name: Install dependencies
        run: poetry install --no-ansi

      - name: Run test
        run: ./tests/ray_deps_test.sh
