name: Smoke tests

on:
  workflow_call:

jobs:
  build:
    name: Example calculate_pi
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install poetry
        uses: Gr1N/setup-poetry@v9

      - name: Install dependencies
        run: poetry install --no-ansi

      - name: Prepare `golem-cluster.tests.yaml`
        run: |
          poetry run python -m utils.apply_overrides -o golem-cluster.tests.yaml golem-cluster.override.1-source-files.yaml golem-cluster.override.2-image.yaml golem-cluster.override.3-disable-stats.yaml golem-cluster.override.4-subnet.yaml
          cat golem-cluster.tests.yaml

      - name: Call `ray up`
        env:
          PYTHONUNBUFFERED: 1
          RUST_LOG: "INFO,ya_erc20_driver::erc20::wallet=debug"
        run: poetry run ray up golem-cluster.tests.yaml -y --no-config-cache

      - name: Run `examples/calculate.pi`
        run: poetry run ray submit golem-cluster.tests.yaml examples/calculate_pi.py

      - name: Call `ray down`
        run: poetry run ray down golem-cluster.tests.yaml -y

      - name: Call `ray-on-golem stop`
        run: poetry run ray-on-golem stop

      - name: Check node creation in logs
        run: poetry run python tests/webserver_logs_test.py ~/.local/share/ray_on_golem/webserver.log 2

      - name: Collects logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-smoke-calculate_pi
          path: |
            /home/runner/.local/share/ray_on_golem/webserver_debug.log
            /home/runner/.local/share/ray_on_golem/yagna.log