name: Smoke tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Smoke tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install poetry
        uses: Gr1N/setup-poetry@v8

      - name: Install dependencies
        run: poetry install --no-ansi

      - name: Prepare `golem-cluster.tests.yaml`
        run: poetry run python -m utils.apply_overrides -o golem-cluster.tests.yaml golem-cluster.override.2-image.yaml golem-cluster.override.3-disable-stats.yaml

      - name: Call `ray up`
        env:
          PYTHONUNBUFFERED: 1
          RUST_LOG: "INFO,ya_erc20_driver::erc20::wallet=debug"
        run: poetry run ray up golem-cluster.tests.yaml -y

      - name: Run `examples/calculate.pi`
        run: poetry run ray submit golem-cluster.tests.yaml examples/calculate_pi.py

      - name: Call `ray down`
        run: poetry run ray down golem-cluster.tests.yaml -y

      - name: Check node creation in logs
        continue-on-error: true
        run: poetry run python tests/smoke.py /tmp/ray_on_golem/webserver_debug.log

      - name: Collects logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: |
            /tmp/ray_on_golem/webserver_debug.log
            /tmp/ray_on_golem/yagna.log