services:
    minio:
        image: minio/minio:latest
        volumes:
            - data:/data
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123
        command: server --console-address ":9001" /data

volumes:
    data:
